# Generated by Django 4.1.7 on 2023-05-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(auto_created=True, default=0),
        ),
    ]
